"""initial migration

Revision ID: 7b4168229ef4
Revises: 
Create Date: 2017-05-16 14:23:48.805498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b4168229ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('html', mysql.LONGTEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=3), nullable=True),
    sa.Column('dateline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('html', mysql.LONGTEXT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=3), nullable=True),
    sa.Column('dateline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['indexs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    op.drop_table('indexs')
    # ### end Alembic commands ###
